name: Terrform Build
on: 
  workflow dispatch:
  push: 
    branches: [ "main" , "master"]
  PR : ["master"]

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: Terraform plan
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v7

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4

    - name: Terraform INIT
      run: terraform init -input=false